services:
  metabase:
    image: metabase/metabase-enterprise:v1.57.x
    volumes:
      - type: bind
        source: ./metabase/metabase_dump.sql
        target: /app/metabase_dump.sql
        read_only: true
        bind:
          create_host_path: false